import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Conecta já",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  );
}
